apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicurio-studio-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: apicurio-studio-operator
  template:
    metadata:
      labels:
        name: apicurio-studio-operator
    spec:
      serviceAccountName: apicurio-studio-operator
      containers:
        - name: apicurio-studio-operator
          image: quay.io/lbroudoux/apicurio-studio-operator:latest
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "apicurio-studio-operator"
